Extension { #name : #MAVisitor }

{ #category : #'*Magritte-Swift' }
MAVisitor >> visitSwiftClassContainer: anObject [
	self visitElementDescription: anObject
]

{ #category : #'*Magritte-Swift' }
MAVisitor >> visitSwiftClassInitContainer: anObject [
	self visitElementDescription: anObject
]

{ #category : #'*Magritte-Swift' }
MAVisitor >> visitSwiftStructContainer: anObject [
	self visitElementDescription: anObject
]
